name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        target: [esp32, pcb, pcb_oled_sh1106, pcb_oled_ssd1306, pcb_lcd_20x4, pcb_lcd_16x2]
    steps:
    - uses: actions/checkout@v1
    - name: Install Python Wheel
      run: pip install wheel
    - name: Install PlatformIO Core
      run: pip install -U https://github.com/platformio/platformio/archive/develop.zip
    - name: Install PlatformIO Espressif32 platform
      run: python -m platformio platform install https://github.com/platformio/platform-espressif32.git#feature/stage
    - name: Compile
      run: |
        mkdir build
        python -m platformio run -e ${{ strategy.matrix.target }}
        cp .pio/build/${{ strategy.matrix.target }}/firmware.bin build/${{ strategy.matrix.target }}.bin
    - name: Package binaries
      uses: actions/upload-artifact@v1
      with:
        name: ${{ strategy.matrix.target }}
        path: build/${{ strategy.matrix.target }}.bin
      if: success() && (github.event_name != 'pull_request') && (${{ strategy.matrix.target }} != 'esp32')
    - name: Upload Binaries
      uses: docker://softprops/action-gh-release
      if: success() && startsWith(github.ref, 'refs/tags/') && (${{ strategy.matrix.target }} != 'esp32')
      with:
        files: build/${{ strategy.matrix.target }}.bin
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}