name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        target: [ESP32CommandStation]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install git wget curl libssl-dev libncurses-dev flex bison gperf python python-pip python-setuptools python-serial python-click python-cryptography python-future python-pyparsing python-pyelftools cmake ninja-build ccache
    - name: Install Python Wheel
      run: pip install wheel
    - name: build
      run: bash .github/build.sh
    - name: Package binaries
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.target }}
        path: build/${{ matrix.target }}.bin
      if: success() && (github.event_name != 'pull_request') && (matrix.target != 'ESP32CommandStation')
    - name: Upload Binaries
      uses: docker://softprops/action-gh-release
      if: success() && startsWith(github.ref, 'refs/tags/') && (matrix.target != 'ESP32CommandStation')
      with:
        files: build/${{ matrix.target }}.bin
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}