name: Test Build

on: [push, pull_request]

strategy:
  matrix:
    env: [esp32, pcb, pcb_oled_sh1106, pcb_oled_ssd1306, pcb_lcd_20x4, pcb_lcd_16x2]

jobs:
  build:
    name: Build (${{ matrix.env }})
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Python Wheel
      run: pip install wheel
    - name: Install PlatformIO Core
      run: pip install -U https://github.com/platformio/platformio/archive/develop.zip
    - name: Install PlatformIO Espressif32 platform
      run: python -m platformio platform install https://github.com/platformio/platform-espressif32.git#feature/stage
    - name: Compile
      run: |
        mkdir build
        python -m platformio run -e ${{ matrix.env }}
        cp .pio/build/${{ matrix.env }}/firmware.bin build/${{ matrix.env }}.bin
    - name: Package binaries
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.env }}
        path: build/${{ matrix.env }}.bin
      if: success() && (github.event_name != 'pull_request') && (${{ matrix.env }} != 'esp32')
    - name: Upload Binaries
      uses: docker://softprops/action-gh-release
      if: success() && startsWith(github.ref, 'refs/tags/') && (${{ matrix.env }} != 'esp32')
      with:
        files: build/${{ matrix.env }}.bin
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}